# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
vi:
  languageCode: vi
  contentDir: content/vi
  title: Nguyễn Thái Hoàng
  params:
    description: Trang web cá nhân của Hoàng
      #   menu:
      #     main:
      #       - name: Hoang
      #         url: '#about'
      #         weight: 1
